name: InventoryKeepChance
version: 0.0.4
api: 5.0.0
main: davidglitch04\InventoryKeepChance\Main
src-namespace-prefix: davidglitch04\InventoryKeepChance
author: DavidGlitch04

commands:
  ikc:
    permission: inventorykeepchance.perm
    description: "Edit inventory retention chance"

permissions:
  inventorykeepchance.perm:
    description: "Edit inventory retention chance"
    default: op